import { useState } from 'react';
import { Archive, Sparkles } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { Page } from '../components/UI';
const DAYS=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'];
export default function Menu(){const {weeks,recipes,preferences,updateMeal,archiveWeek}=useApp();const active=weeks.find(w=>!w.archived);const [suggestions,setSuggestions]=useState<string[]>([]);const [loading,setLoading]=useState(false);
 const suggest=async(day:string,slot:'lunch'|'dinner')=>{setLoading(true);try{const res=await fetch('/.netlify/functions/suggest-recipes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({recipes,recentMeals:weeks.filter(w=>w.archived).slice(0,6).flatMap(w=>Object.values(w.days).flatMap(d=>[d.lunch,d.dinner])).filter(Boolean),mealType:'comida normal',preferences})});const data=await res.json();setSuggestions((data.suggestions||[]).map((x:{name:string})=>x.name));if(!res.ok)throw new Error(data.error)}catch{setSuggestions(['Tacos de pollo con verduras','Ensalada de atún con tostadas','Picadillo de res con arroz','Quesadillas con frijoles'])}finally{setLoading(false)}};
 if(!active)return null;return <Page title="Menú semanal" subtitle="Comida y cena de cada día" action={<button className="secondary small" onClick={archiveWeek}><Archive size={17}/>Archivar</button>}>
 {suggestions.length>0&&<div className="suggestions"><div><strong>Ideas de Alacena</strong><button className="icon-btn" onClick={()=>setSuggestions([])}>×</button></div>{suggestions.map(s=><span key={s}>{s}</span>)}</div>}
 <div className="week-grid">{DAYS.map(day=><article className="day-card" key={day}><h3>{day}</h3>{(['lunch','dinner'] as const).map(slot=><label key={slot}><span>{slot==='lunch'?'Comida':'Cena'}<button type="button" className="spark" onClick={()=>suggest(day,slot)} disabled={loading}><Sparkles size={15}/></button></span><input value={active.days[day]?.[slot]||''} onChange={e=>updateMeal(day,slot,e.target.value)} placeholder="Escribe o elige una receta…"/></label>)}</article>)}</div>
 {weeks.filter(w=>w.archived).length>0&&<details className="history"><summary>Historial de semanas ({weeks.filter(w=>w.archived).length})</summary>{weeks.filter(w=>w.archived).map(w=><div className="card" key={w.id}><strong>{w.label} · {w.week_start}</strong></div>)}</details>}</Page>}
