import { useState } from 'react';
import { ChevronDown, ChevronUp, ListPlus, Plus, Trash2 } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { Empty, Page } from '../components/UI';
export default function Recipes(){const {recipes,saveRecipe,deleteRecipe,addRecipeToList}=useApp();const [open,setOpen]=useState<string>();const [show,setShow]=useState(false);const [name,setName]=useState('');const [ingredients,setIngredients]=useState('');const [notes,setNotes]=useState('');
 const submit=async(e:React.FormEvent)=>{e.preventDefault();await saveRecipe({name,ingredients:ingredients.split('\n').map(x=>x.trim()).filter(Boolean),notes});setName('');setIngredients('');setNotes('');setShow(false)};
 return <Page title="Recetario" subtitle={`${recipes.length} recetas guardadas`} action={<button className="primary small" onClick={()=>setShow(!show)}><Plus size={17}/>Nueva</button>}>
 {show&&<form className="card recipe-form" onSubmit={submit}><input placeholder="Nombre de la receta" value={name} onChange={e=>setName(e.target.value)} required/><textarea placeholder="Ingredientes, uno por línea" value={ingredients} onChange={e=>setIngredients(e.target.value)} rows={5} required/><textarea placeholder="Preparación y notas" value={notes} onChange={e=>setNotes(e.target.value)} rows={4}/><button className="primary">Guardar receta</button></form>}
 {recipes.length===0?<Empty>Aún no hay recetas.</Empty>:recipes.map(r=><article className="card recipe" key={r.id}><button className="recipe-title" onClick={()=>setOpen(open===r.id?undefined:r.id)}><strong>{r.name}</strong>{open===r.id?<ChevronUp/>:<ChevronDown/>}</button>{open===r.id&&<div className="recipe-body"><h4>Ingredientes</h4><ul>{r.ingredients.map((i,n)=><li key={n}>{i}</li>)}</ul>{r.notes&&<><h4>Preparación</h4><p>{r.notes}</p></>}<div className="actions"><button className="secondary" onClick={()=>addRecipeToList(r)}><ListPlus size={17}/>Agregar a lista</button><button className="ghost danger" onClick={()=>deleteRecipe(r.id)}><Trash2 size={17}/>Eliminar</button></div></div>}</article>)}</Page>}
