import { useState } from 'react';
import { Camera, ChevronDown, ChevronUp, Sparkles } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { fileToBase64, money } from '../lib/utils';
import { isConfigured, supabase } from '../lib/supabase';
import { CATEGORIES, type Category, type PurchaseItem } from '../types';
import { Empty, Page } from '../components/UI';
export default function Tickets(){const {purchases,addPurchase}=useApp();const [store,setStore]=useState('HEB');const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [file,setFile]=useState<File>();const [items,setItems]=useState<PurchaseItem[]>([]);const [total,setTotal]=useState(0);const [reading,setReading]=useState(false);const [open,setOpen]=useState<string>();const [toPantry,setToPantry]=useState(true);
 const read=async()=>{if(!file)return;setReading(true);try{const imageBase64=await fileToBase64(file);const res=await fetch('/.netlify/functions/parse-receipt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({imageBase64,mediaType:file.type,store})});const data=await res.json();if(!res.ok)throw new Error(data.error);setItems(data.items||[]);setTotal(Number(data.total)||0)}catch(e){alert(e instanceof Error?e.message:'No se pudo leer el ticket')}finally{setReading(false)}};
 const save=async()=>{let image_path:string|null=null;if(file&&isConfigured){const safe=`${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error}=await supabase.storage.from('receipts').upload(safe,file,{contentType:file.type,upsert:false});if(error){alert(`No se pudo subir la imagen: ${error.message}`);return}image_path=safe;} await addPurchase({store,purchase_date:date,image_path,total,status:'confirmed',purchase_items:items},toPantry);setItems([]);setTotal(0);setFile(undefined);alert('Ticket guardado')};
 return <Page title="Tickets" subtitle="Registra y revisa tus compras"><div className="card ticket-form"><div className="form-grid"><label>Tienda<select value={store} onChange={e=>setStore(e.target.value)}><option>HEB</option><option>Calii</option><option>Calimax</option><option>Otro</option></select></label><label>Fecha<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><label className="file-drop"><Camera/><span>{file?file.name:'Tomar foto o elegir captura'}</span><input type="file" accept="image/*" capture="environment" onChange={e=>setFile(e.target.files?.[0])}/></label><button className="primary" onClick={read} disabled={!file||reading}><Sparkles size={18}/>{reading?'Leyendo…':'Leer ticket con IA'}</button></div>
 {items.length>0&&<div className="card"><h3>Revisa antes de guardar</h3>{items.map((it,i)=><div className="ticket-edit" key={i}><input value={it.name} onChange={e=>setItems(v=>v.map((x,n)=>n===i?{...x,name:e.target.value}:x))}/><select value={it.category} onChange={e=>setItems(v=>v.map((x,n)=>n===i?{...x,category:e.target.value as Category}:x))}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select><input type="number" step="0.01" value={it.total_price} onChange={e=>setItems(v=>v.map((x,n)=>n===i?{...x,total_price:Number(e.target.value)}:x))}/></div>)}<label>Total<input type="number" step="0.01" value={total} onChange={e=>setTotal(Number(e.target.value))}/></label><label className="toggle"><span><strong>Agregar productos a la despensa</strong><small>Los artículos detectados aumentarán tu inventario.</small></span><input type="checkbox" checked={toPantry} onChange={e=>setToPantry(e.target.checked)}/></label><button className="primary" onClick={save}>Guardar compra</button></div>}
 <h3 className="section-title">Compras recientes</h3>{purchases.length===0?<Empty>Aún no has guardado tickets.</Empty>:purchases.map(p=><article className="card purchase" key={p.id}><button onClick={()=>setOpen(open===p.id?undefined:p.id)}><span><strong>{p.store}</strong><small>{p.purchase_date}</small></span><b>{money(p.total)}</b>{open===p.id?<ChevronUp/>:<ChevronDown/>}</button>{open===p.id&&<div>{p.purchase_items?.map((i,n)=><p key={n}><span>{i.name}</span><b>{money(i.total_price)}</b></p>)}</div>}</article>)}</Page>}
